import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "../globals.css";
import { SessionProvider } from "next-auth/react";
import { MqttProvider } from "@/contexts/MqttContext";
import { SidebarInset, SidebarProvider } from "@repo/ui/components/ui/sidebar";
import Header from "@repo/ui/components/elements/Header";
import MqttConnectionStatus from "@/components/common/MqttConnectionStatus";
import UserProfile from "@/components/common/UserProfile";
import { AppSidebar } from "@repo/ui/components/elements/AppSidebar"
import { homeSidebarLinks } from "@/lib/sidebar-links"
import { Toaster } from "@repo/ui/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function DashboardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} font-poppins antialiased`}
			>
				<SessionProvider>
					<MqttProvider>
						<div className="h-screen flex flex-col [--header-height:100px]">
							<SidebarProvider className="flex flex-col flex-1 min-h-0">
								<Header
									title="Trailer Dashboard"
									subtitle="View trailer metrics"
								>
									{/* <UserTrailersDropdown /> */}
									{/* <SharedTrailersDropdown /> */}
									<MqttConnectionStatus />
									<UserProfile />
								</Header>
								<div className="flex flex-1 min-h-0">
									<AppSidebar data={{ links: homeSidebarLinks }} />
									<SidebarInset className="flex-1 min-h-0">
										<div className="flex flex-col h-full gap-4 p-4">
											{children}
										</div>
									</SidebarInset>
								</div>
							</SidebarProvider>
						</div>
					</MqttProvider>
				</SessionProvider>
				<Toaster />
			</body>
		</html>
	);
}
