import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "../globals.css";
import { SessionProvider } from "next-auth/react";
import { MqttProvider } from "@/contexts/MqttContext";
import { SidebarInset, SidebarProvider } from "@repo/ui/components/ui/sidebar";
import Header from "@repo/ui/components/elements/Header";
import MqttConnectionStatus from "@/components/common/MqttConnectionStatus";
import UserProfile from "@/components/common/UserProfile";
import { AppSidebar } from "@repo/ui/components/elements/AppSidebar"
import { sidebarLinks } from "@/lib/sidebar-links"
import CustomSidebarComponent from "@/components/common/CustomSidebarComponent";
import TrailerBreadCrumbs from "@/components/common/TrailerBreadCrumbs";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function SharedTrailersLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} font-poppins antialiased`}
			>
				<SessionProvider>
					<MqttProvider>
						<div className="h-screen flex flex-col [--header-height:100px]">
							<SidebarProvider className="flex flex-col flex-1 min-h-0">
								<Header
									title="Trailer Dashboard"
									subtitle="View trailer metrics"
								>
									<MqttConnectionStatus />
									<UserProfile />
								</Header>
								<div className="flex flex-1 min-h-0">
									<CustomSidebarComponent>
										{children}
									</CustomSidebarComponent>
								</div>
							</SidebarProvider>
						</div>
					</MqttProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
